name: Decentraland Data Collector

on:
  schedule:
    - cron: "*/5 * * * *"  # This runs the workflow every 5 minutes
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pydrive2 requests

      - name: Run collector script
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          PYTHONIOENCODING: utf-8
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
        run: python collector.py
